import Foundation

enum AccessibilityID {
    static let sidebarDownload = "sidebar-download"
    static let sidebarXMedia = "sidebar-x-media"
    static let sidebarConvert = "sidebar-convert"
    static let sidebarTrim = "sidebar-trim"
    static let sidebarTranscribe = "sidebar-transcribe"
    static let sidebarQueue = "sidebar-queue"
    static let sidebarHistory = "sidebar-history"
    static let workspaceDropOverlay = "workspace-drop-overlay"

    static let downloadURLField = "download-url-field"
    static let downloadInspectButton = "download-inspect-button"
    static let downloadQueueButton = "download-queue-button"
    static let downloadAuthPicker = "download-auth-picker"
    static let downloadConfigureAuthButton = "download-configure-auth-button"
    static let downloadAuthSummary = "download-auth-summary"
    static let downloadSubtitlePolicyPicker = "download-subtitle-policy-picker"
    static let downloadSubtitleFormatPicker = "download-subtitle-format-picker"
    static let downloadInlineStatusCard = "download-inline-status-card"
    static let downloadInlineStatusTitle = "download-inline-status-title"
    static let downloadInlineStatusMessage = "download-inline-status-message"
    static let downloadInlineProgress = "download-inline-progress"
    static let downloadInlineOpenQueueButton = "download-inline-open-queue-button"
    static let downloadInlineCancelButton = "download-inline-cancel-button"
    static let authSheetProfilePicker = "auth-sheet-profile-picker"
    static let authSheetStepPicker = "auth-sheet-step-picker"
    static let authSheetStrategyPicker = "auth-sheet-strategy-picker"
    static let authSheetSaveButton = "auth-sheet-save-button"
    static let authSheetDeleteButton = "auth-sheet-delete-button"
    static let convertOpenButton = "convert-open-button"
    static let convertQueueButton = "convert-queue-button"
    static let convertSubtitleToggle = "convert-subtitle-toggle"
    static let trimOpenButton = "trim-open-button"
    static let trimQueueButton = "trim-queue-button"
    static let trimSubtitleToggle = "trim-subtitle-toggle"
    static let transcribeOpenButton = "transcribe-open-button"
    static let transcribeQueueButton = "transcribe-queue-button"
    static let transcribeFormatPicker = "transcribe-format-picker"
    static let transcribeFormatValue = "transcribe-format-value"
    static let queueList = "queue-list"
    static let queueJobCancelButton = "queue-job-cancel-button"
    static let queueJobRetryButton = "queue-job-retry-button"
    static let settingsOverwriteToggle = "settings-overwrite-toggle"
    static let updateCancelButton = "update-cancel-button"
    static let updateRetryButton = "update-retry-button"
    static let historyList = "history-list"
    static let historyEntryRerunButton = "history-entry-rerun-button"
}
